pub enum ItemTag {
  Angel,
  Baby,
  Battery,
  Bob,
  Book,
  Dead,
  Devil,
  Fly,
  Food,
  Guppy,
  LazarusShared,
  LazarusSharedGlobal,
  Mom,
  MonsterManual,
  Mushroom,
  NoCanTrip,
  NoChallenge,
  NoDaily,
  NoEden,
  NoGreed,
  NoKeeper,
  NoLostBr,
  Offensive,
  Poop,
  Quest,
  Spider,
  Stars,
  Summonable,
  Syringe,
  TearsUp,
  Tech,
  UniqueFamiliar
}

impl ItemTag {
  pub fn name(&self) -> &'static str {
    match self {
      ItemTag::Angel => "Angel",
      ItemTag::Baby => "Baby",
      ItemTag::Battery => "Battery",
      ItemTag::Bob => "Bob",
      ItemTag::Book => "Book",
      ItemTag::Dead => "Dead",
      ItemTag::Devil => "Devil",
      ItemTag::Fly => "Fly",
      ItemTag::Food => "Food",
      ItemTag::Guppy => "Guppy",
      ItemTag::LazarusShared => "LazarusShared",
      ItemTag::LazarusSharedGlobal => "LazarusSharedGlobal",
      ItemTag::Mom => "Mom",
      ItemTag::MonsterManual => "MonsterManual",
      ItemTag::Mushroom => "Mushroom",
      ItemTag::NoCanTrip => "NoCanTrip",
      ItemTag::NoChallenge => "NoChallenge",
      ItemTag::NoDaily => "NoDaily",
      ItemTag::NoEden => "NoEden",
      ItemTag::NoGreed => "NoGreed",
      ItemTag::NoKeeper => "NoKeeper",
      ItemTag::NoLostBr => "NoLostBr",
      ItemTag::Offensive => "Offensive",
      ItemTag::Poop => "Poop",
      ItemTag::Quest => "Quest",
      ItemTag::Spider => "Spider",
      ItemTag::Stars => "Stars",
      ItemTag::Summonable => "Summonable",
      ItemTag::Syringe => "Syringe",
      ItemTag::TearsUp => "TearsUp",
      ItemTag::Tech => "Tech",
      ItemTag::UniqueFamiliar => "UniqueFamiliar"
    }
  }
}